CREATE TABLE config_versions (
  id UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
  updated_on TIMESTAMP WITH TIME ZONE NOT NULL,
  hash BYTEA NOT NULL
);

ALTER TABLE destinations
DROP COLUMN path,
ADD COLUMN code VARCHAR NOT NULL UNIQUE;

ALTER TABLE destinations
ADD COLUMN path VARCHAR NOT NULL;

ALTER TABLE sources
ADD COLUMN code VARCHAR NOT NULL UNIQUE;